[tool.poetry]
name = "netbox-lists"
version = "1.0.0"
description = ""
authors = ["Devon Mar <devonm@mdmm.ca>"]

[tool.poetry.dependencies]
python = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8"
pynetbox = "^6.1.3"
requests = "^2.26.0"
isort = "^5.10.1"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
